// Generated by Dart Safe Data Class Generator. * Change this header on extension settings *
// ignore_for_file: type=lint
import 'package:bloc/bloc.dart';
import 'package:flutter/foundation.dart';
import 'package:freezed_annotation/freezed_annotation.dart';

import 'package:flutter_kasir/data/datasource/auth_remote_datasource.dart';
import 'package:flutter_kasir/data/models/response/Auth_Response_Model.dart';

part 'login_bloc.freezed.dart';
part 'login_event.dart';
part 'login_state.dart';

class LoginBloc extends Bloc<LoginEvent, LoginState> {
  final AuthRemoteDatasource authRemoteDatasource;
  LoginBloc(
    this.authRemoteDatasource,
  ) : super(const _Initial()) {
    on<_Login>((event, emit) async{
     emit(const _Loading());
     final response = await authRemoteDatasource.login(event.email, event.password,);
     response.fold((l) => emit(_Error(l)), 
     (r) => emit(_Success(r)));
    });
  }
}
